### PR TITLE
fix: cubeAxesSerializer colors

### PR DESCRIPTION
**Pull request by banesullivan**
Work in progress... still need to figure out how to change the color of the gridlines:

Screen Shot 2023-01-18 at 10 54 11 PM

### CODE REVIEW

**Comment by jourdain** [comment]
The CI needs you to run black on the file you modified.

**Comment by jourdain** [comment]
So to control the grid (color..), you need to update/set the color on the `actor.GetProperty()`.

**Comment by jourdain** [comment]
Since it is an actor you need to do something similar to what we do on the actor serializer. Especially [that part](https://github.com/Kitware/VTK/blob/master/Web/Python/vtkmodules/web/render_window_serializer.py#L457-L470) for grabbing the vtkProperty.

**Comment by banesullivan** [comment]
Pushed changes in progress and added a validation example using PyVista and `VtkLocalView` any version of PyVista should work in this example (no need for my PyVista-Trame development branch)

**Comment by jourdain** [comment]
merged on #12

**Pull request closed without merging**
