### PR TITLE
fix(serializer): Better handling of actor user matrix

### LINKED ISSUE #50: BUG: `axes_actor_serializer` raises unexpected `vtkTransform` `AttributeError`
The following line of code
https://github.com/Kitware/trame-vtk/blob/487c4c03054c5a6dad3a671760d53a2375d3119f/trame_vtk/modules/vtk/serializers/actors.py#L320
unexpectedly raises 
```python 
AttributeError: 'vtkmodules.vtkCommonTransforms.vtkMatrixToLinearTr' object has no attribute 'GetTranspose
```
for valid transforms, e.g. [`vtkMatrixToLinearTransform`](https://vtk.org/doc/nightly/html/classvtkMatrixToLinearTransform.html), which do not implement `GetTranspose`.

This error is raised, for example, when implicitly setting `UserTransform` via `SetUserMatrix`. 
E.g. to reproduce the bug, do:
```python
from vtk import vtkAxesActor, vtkMatrix4x4
# Create actor with user matrix
actor = vtkAxesActor()
matrix = vtkMatrix4x4()
actor.SetUserMatrix(matrix)

# Apply transform
user_matrix = [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1]
if actor.GetUserTransform():
    matrix = vtkMatrix4x4()
    actor.GetUserTransform().GetTranspose(matrix)
    for i in range(4):
        for j in range(4):
            idx = i + 4 * j
            user_matrix[idx] = matrix.GetElement(j, i)
```

This bug showed up recently in PyVista CI testing for PR [pyvista#5019](https://github.com/pyvista/pyvista/pull/5029). Here's a [link](https://github.com/pyvista/pyvista/actions/runs/6434397659/job/17473554431?pr=5029#step:11:1100)  to the `AttributeError` being raised in the test. The cause of the error was traced back to the fact that the axes internally make a call to `actor.SetUserMatrix(matrix)` exactly as shown above.

A suggested fix is to replace:
https://github.com/Kitware/trame-vtk/blob/487c4c03054c5a6dad3a671760d53a2375d3119f/trame_vtk/modules/vtk/serializers/actors.py#L318-L320
with:
``` python
if actor.GetUserMatrix():
    matrix = actor.GetUserMatrix()
    matrix.Transpose()
```

### PR DESCRIPTION
**Pull request by user27182**
Resolves #50

### CODE REVIEW

**Comment by jourdain** [comment]
`trame_vtk/modules/vtk/serializers/actors.py:3:1: F401 'vtkmodules.vtkCommonMath.vtkMatrix4x4' imported but unused`

**Comment by jourdain** [comment]
FYI, the new version of PyVista is changing its initial camera point of view? That led me to update a baseline. But both local and remote are consistent so I feel confident. 

But, the [local rendering of volume rendering](https://github.com/Kitware/trame-vtk/blob/master/examples/validation/PyVistaVolumeRendering.py) is now broken with PyVista. (FYI @banesullivan, @alesgenova)

**Comment by banesullivan** [comment]
> new version of PyVista is changing its initial camera point of view

I'm not aware of this... and I hope not the case. Not sure what you are referring to.

**Comment by jourdain** [comment]
new vs old

**Comment by user27182** [comment]
> New PyVista 
> vs old PyVista

@jourdain Can you please clarify which versions of old and new you are referring to?

A bug with the orientation/direction of `pyvista.Sphere` was recently patched and released in PyVista 0.42, I believe, with PR [pyvista#4674](https://github.com/pyvista/pyvista/pull/4674). This resulted in scalar values being plotted differently for `pyvista.Sphere` objects, and similar regression test images had to be updated accordingly. The changes are shared below (see direct link [here](https://github.com/pyvista/pyvista/pull/4674/files#diff-8ec3a8a9f13588c894233d8c2c81d63d62e882f01c846c7999e82164fc8f6db0)).

Perhaps this is the same cause of the differences you're seeing with the trame PyVista tests? Though in your image the spheres appear different by a 180 degree rotation, whereas the image below looks more like a 90 degree rotation.

image

**Comment by jourdain** [comment]
When running `python ./examples/validation/PyVistaInt64.py` with 

```
vtk                  9.2.6
pyvista              0.40.1
```

I get  
Screenshot 2023-10-10 at 8 21 14 AM

Then with `pyvista==0.42.3`, I get

Screenshot 2023-10-10 at 8 20 48 AM

**Pull request merged**
